version: '3'

services: 
  airflow:
    build: ./
    container_name: airflow
    ports:      
      - '8080:8080'
    volumes:
      - ../dags:/usr/local/airflow/dags
  minio:
    image: docker.io/bitnami/minio:2021
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniominio
    volumes:
      - 'minio_data:/data'
volumes:
  minio_data:
    driver: local